version: "3"
services:
  web:
    container_name: django_userpolls_web
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - ${WEB_STATIC}:/var/www/static/
    ports:
      - 127.0.0.1:8005:8000
    networks:
      - userpolls_network
    depends_on:
      - db
  db:
    container_name: django_userpolls_db
    image: postgres:13-alpine
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - userpolls_db:/var/lib/postgresql/data
    networks:
      - userpolls_network
volumes:
  userpolls_db:
networks:
  userpolls_network:
