# Generated by Django 3.1.6 on 2021-02-06 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamthemen', '0003_remove_topic_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='users_downvoted',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
