# Generated by Django 3.1.6 on 2021-02-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamthemen', '0004_topic_users_downvoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='users_downvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='users_upvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
