# Generated by Django 3.1.6 on 2021-02-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamthemen', '0005_auto_20210207_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
