# Generated by Django 3.1.6 on 2021-02-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamthemen', '0006_auto_20210207_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
