# Generated by Django 3.1.6 on 2021-02-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamthemen', '0011_auto_20210211_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTTVEmote',
            new_name='Emote',
        ),
        migrations.DeleteModel(
            name='FFZEmote',
        ),
        migrations.DeleteModel(
            name='TwitchEmote',
        ),
        migrations.RenameField(
            model_name='emote',
            old_name='imageType',
            new_name='provider',
        ),
    ]
