# Generated by Django 3.1.6 on 2021-02-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamthemen', '0012_auto_20210211_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emote',
            old_name='_id',
            new_name='emote_id',
        ),
    ]
